/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Backend API
 * OpenAPI spec version: 0.1.0
 */
import type { NoteUpdateContent } from "./noteUpdateContent";
import type { NoteUpdateLinks } from "./noteUpdateLinks";
import type { NoteUpdateTitle } from "./noteUpdateTitle";

export interface NoteUpdate {
  content?: NoteUpdateContent;
  links?: NoteUpdateLinks;
  title?: NoteUpdateTitle;
}
