/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Backend API
 * OpenAPI spec version: 0.1.0
 */

export interface NoteCreate {
  content?: string;
  links?: string[];
  title?: string;
}
