/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Backend API
 * OpenAPI spec version: 0.1.0
 */

export interface NoteRead {
  content?: string;
  created_at: string;
  id: string;
  links?: string[];
  title?: string;
  updated_at: string;
  vault_id: string;
}
