/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Backend API
 * OpenAPI spec version: 0.1.0
 */
import type { RegisterRequestDisplayName } from "./registerRequestDisplayName";

export interface RegisterRequest {
  display_name?: RegisterRequestDisplayName;
  email: string;
  password: string;
}
