/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Backend API
 * OpenAPI spec version: 0.1.0
 */
import type { UserRead } from "./userRead";

export interface TokenResponse {
  access_token: string;
  token_type?: string;
  user: UserRead;
}
