/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Backend API
 * OpenAPI spec version: 0.1.0
 */
import type { UserReadDisplayName } from "./userReadDisplayName";

export interface UserRead {
  created_at: string;
  display_name?: UserReadDisplayName;
  email: string;
  id: string;
  updated_at: string;
}
