/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Backend API
 * OpenAPI spec version: 0.1.0
 */
import type { VaultCreateTheme } from "./vaultCreateTheme";

export interface VaultCreate {
  name: string;
  theme?: VaultCreateTheme;
}
