/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * Backend API
 * OpenAPI spec version: 0.1.0
 */
import type { VaultUpdateName } from "./vaultUpdateName";
import type { VaultUpdateTheme } from "./vaultUpdateTheme";

export interface VaultUpdate {
  name?: VaultUpdateName;
  theme?: VaultUpdateTheme;
}
